# Generated by Django 4.2.4 on 2024-06-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='conflict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_items', to='shop.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='dosage',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
