# Generated by Django 4.2.4 on 2024-06-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_drugconflict_remove_item_conflict_drugconflictitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugconflictitem',
            name='conflict',
        ),
        migrations.RemoveField(
            model_name='drugconflictitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='conflicts',
        ),
        migrations.DeleteModel(
            name='DrugConflict',
        ),
        migrations.DeleteModel(
            name='DrugConflictItem',
        ),
    ]
