# Generated by Django 4.2.4 on 2024-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_drugconflictitem_conflict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_prescription',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
