# Generated by Django 4.2.4 on 2024-06-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_pdf_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_prescription', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='pdf_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.prescription'),
        ),
    ]
