# Generated by Django 4.2.4 on 2024-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_prescription_alter_order_pdf_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('confilt', models.CharField(max_length=50, verbose_name='self')),
            ],
        ),
    ]
