# Generated by Django 4.2.4 on 2024-06-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_activedrug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activedrug',
            name='confilt',
        ),
        migrations.AddField(
            model_name='activedrug',
            name='conflicts',
            field=models.ManyToManyField(blank=True, to='shop.activedrug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='active_drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.activedrug'),
        ),
    ]
