# Generated by Django 4.2.4 on 2024-06-16 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_activedrug_confilt_activedrug_conflicts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pdf_prescription',
        ),
        migrations.AddField(
            model_name='prescription',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order'),
        ),
    ]
